[33mWARNING[0m:  [21-09-2024 02:37:47] chroma_server_nofile is not supported on Windows. chroma_server_nofile will not be set.
[32mINFO[0m:     [21-09-2024 02:37:47] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [21-09-2024 02:37:47] Starting component System
[36mDEBUG[0m:    [21-09-2024 02:37:47] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [21-09-2024 02:37:47] Starting component SqliteDB
[36mDEBUG[0m:    [21-09-2024 02:37:47] Starting component QuotaEnforcer
[36mDEBUG[0m:    [21-09-2024 02:37:47] Starting component Posthog
[36mDEBUG[0m:    [21-09-2024 02:37:47] Starting component LocalSegmentManager
[36mDEBUG[0m:    [21-09-2024 02:37:47] Starting component SegmentAPI
[32mINFO[0m:     [21-09-2024 02:37:47] Started server process [[36m8848[0m]
[32mINFO[0m:     [21-09-2024 02:37:47] Waiting for application startup.
[32mINFO[0m:     [21-09-2024 02:37:47] Application startup complete.
[32mINFO[0m:     [21-09-2024 02:37:47] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [21-09-2024 02:39:22] ::1:62248 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:39:22] ::1:62248 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:42:17] ::1:62368 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:42:17] ::1:62368 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:42:17] ::1:62369 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:42:37] ::1:62391 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:42:37] ::1:62391 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [21-09-2024 02:42:37] Collection collection_name already exists
Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 105, in receive
    return self.receive_nowait()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 601, in create_collection
    await to_thread.run_sync(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 590, in process_create_collection
    return self._api.create_collection(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\segment.py", line 176, in create_collection
    coll, created = self._sysdb.create_collection(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\db\mixins\sysdb.py", line 227, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection collection_name already exists
[32mINFO[0m:     [21-09-2024 02:42:37] ::1:62392 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [21-09-2024 02:45:47] ::1:62514 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:45:47] ::1:62514 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [21-09-2024 02:45:47] Collection collection_name already exists
Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 105, in receive
    return self.receive_nowait()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 601, in create_collection
    await to_thread.run_sync(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 590, in process_create_collection
    return self._api.create_collection(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\segment.py", line 176, in create_collection
    coll, created = self._sysdb.create_collection(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\db\mixins\sysdb.py", line 227, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection collection_name already exists
[32mINFO[0m:     [21-09-2024 02:45:47] ::1:62515 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [21-09-2024 02:46:09] ::1:62568 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:46:09] ::1:62568 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [21-09-2024 02:46:09] Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got collection_name+_2
Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 105, in receive
    return self.receive_nowait()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 601, in create_collection
    await to_thread.run_sync(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 590, in process_create_collection
    return self._api.create_collection(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\segment.py", line 160, in create_collection
    check_index_name(name)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\segment.py", line 75, in check_index_name
    raise ValueError(msg)
ValueError: Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got collection_name+_2
[32mINFO[0m:     [21-09-2024 02:46:09] ::1:62569 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [21-09-2024 02:46:38] ::1:62590 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:46:38] ::1:62590 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:46:38] ::1:62591 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 02:46:39] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [21-09-2024 02:46:39] ::1:62591 - "POST /api/v1/collections/03c51dfe-79fc-4c70-b4b6-a887b11333a2/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:49:50] ::1:62963 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:49:50] ::1:62963 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:49:50] ::1:62964 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:49:50] ::1:62964 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 02:49:50] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [21-09-2024 02:49:50] ::1:62964 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/add HTTP/1.1" 201
[32mINFO[0m:     [21-09-2024 02:49:50] ::1:62964 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:50:11] ::1:62988 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:50:11] ::1:62988 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [21-09-2024 02:50:11] Collection Students already exists
Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 105, in receive
    return self.receive_nowait()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 601, in create_collection
    await to_thread.run_sync(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 590, in process_create_collection
    return self._api.create_collection(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\segment.py", line 176, in create_collection
    coll, created = self._sysdb.create_collection(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\db\mixins\sysdb.py", line 227, in create_collection
    raise UniqueConstraintError(f"Collection {name} already exists")
chromadb.db.base.UniqueConstraintError: Collection Students already exists
[32mINFO[0m:     [21-09-2024 02:50:11] ::1:62992 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [21-09-2024 02:51:02] ::1:63045 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:51:02] ::1:63045 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [21-09-2024 02:51:02] Collection students does not exist.
Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 105, in receive
    return self.receive_nowait()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 637, in get_collection
    await to_thread.run_sync(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\segment.py", line 251, in get_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection students does not exist.
[32mINFO[0m:     [21-09-2024 02:51:02] ::1:63046 - "GET /api/v1/collections/students?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [21-09-2024 02:51:31] ::1:63058 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:51:31] ::1:63058 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[31mERROR[0m:    [21-09-2024 02:51:31] Collection students does not exist.
Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 105, in receive
    return self.receive_nowait()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 100, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 118, in receive
    return receiver.item
AttributeError: 'MemoryObjectItemReceiver' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 120, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 76, in catch_exceptions_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 189, in __call__
    with collapse_excgroups():
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 93, in collapse_excgroups
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 90, in check_http_version_middleware
    return await call_next(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 165, in call_next
    raise app_exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 133, in async_wrapper
    return await f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\server\fastapi\__init__.py", line 637, in get_collection
    await to_thread.run_sync(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 146, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\Shashwat.Sharma\AppData\Local\Programs\Python\Python310\lib\site-packages\chromadb\api\segment.py", line 251, in get_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection students does not exist.
[32mINFO[0m:     [21-09-2024 02:51:31] ::1:63059 - "GET /api/v1/collections/students?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [21-09-2024 02:51:41] ::1:63072 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:51:41] ::1:63072 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:51:41] ::1:63073 - "GET /api/v1/collections/Students?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:51:41] ::1:63073 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [21-09-2024 02:51:41] Add of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 02:51:41] Add of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 02:51:41] Add of existing embedding ID: id3
[33mWARNING[0m:  [21-09-2024 02:51:41] Insert of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 02:51:41] Insert of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 02:51:41] Insert of existing embedding ID: id3
[32mINFO[0m:     [21-09-2024 02:51:41] ::1:63073 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/add HTTP/1.1" 201
[32mINFO[0m:     [21-09-2024 02:51:41] ::1:63073 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:53:13] ::1:63145 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:53:13] ::1:63145 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:53:13] ::1:63146 - "GET /api/v1/collections/Students?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 02:53:13] ::1:63146 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [21-09-2024 02:53:13] Add of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 02:53:13] Add of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 02:53:13] Add of existing embedding ID: id3
[33mWARNING[0m:  [21-09-2024 02:53:13] Insert of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 02:53:13] Insert of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 02:53:13] Insert of existing embedding ID: id3
[32mINFO[0m:     [21-09-2024 02:53:13] ::1:63146 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/add HTTP/1.1" 201
[32mINFO[0m:     [21-09-2024 02:53:13] ::1:63146 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:49:29] ::1:65485 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:49:29] ::1:65485 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:49:29] ::1:65486 - "GET /api/v1/collections/Students?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:49:29] ::1:65486 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [21-09-2024 03:49:29] Add of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 03:49:29] Add of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 03:49:29] Add of existing embedding ID: id3
[33mWARNING[0m:  [21-09-2024 03:49:29] Insert of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 03:49:29] Insert of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 03:49:29] Insert of existing embedding ID: id3
[32mINFO[0m:     [21-09-2024 03:49:29] ::1:65486 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/add HTTP/1.1" 201
[32mINFO[0m:     [21-09-2024 03:49:29] ::1:65486 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:49:47] ::1:65507 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:49:47] ::1:65507 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:49:47] ::1:65508 - "GET /api/v1/collections/Students?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:49:48] ::1:65508 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [21-09-2024 03:49:48] Add of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 03:49:48] Add of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 03:49:48] Add of existing embedding ID: id3
[33mWARNING[0m:  [21-09-2024 03:49:48] Insert of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 03:49:48] Insert of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 03:49:48] Insert of existing embedding ID: id3
[32mINFO[0m:     [21-09-2024 03:49:48] ::1:65508 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/add HTTP/1.1" 201
[32mINFO[0m:     [21-09-2024 03:49:48] ::1:65508 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:50:22] ::1:65529 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:50:22] ::1:65529 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:50:22] ::1:65530 - "GET /api/v1/collections/Students?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:50:22] ::1:65530 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [21-09-2024 03:50:22] Add of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 03:50:22] Add of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 03:50:22] Add of existing embedding ID: id3
[33mWARNING[0m:  [21-09-2024 03:50:22] Insert of existing embedding ID: id1
[33mWARNING[0m:  [21-09-2024 03:50:22] Insert of existing embedding ID: id2
[33mWARNING[0m:  [21-09-2024 03:50:22] Insert of existing embedding ID: id3
[32mINFO[0m:     [21-09-2024 03:50:22] ::1:65530 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/add HTTP/1.1" 201
[32mINFO[0m:     [21-09-2024 03:50:22] ::1:65530 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:50:52] ::1:49172 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:50:52] ::1:49172 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 03:50:52] Collection Students already exists, returning existing collection.
[32mINFO[0m:     [21-09-2024 03:50:52] ::1:49173 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:51:58] ::1:49232 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:51:58] ::1:49232 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 03:51:58] Collection Students already exists, returning existing collection.
[32mINFO[0m:     [21-09-2024 03:51:58] ::1:49233 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:51:59] ::1:49233 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:59:03] ::1:49763 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:59:03] ::1:49763 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 03:59:03] Collection Students already exists, returning existing collection.
[32mINFO[0m:     [21-09-2024 03:59:03] ::1:49764 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 03:59:14] ::1:49767 - "POST /api/v1/collections/705b5b9a-8355-415e-9b12-a623f6c7c66d/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 04:18:18] ::1:50647 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 04:18:18] ::1:50647 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 04:18:18] ::1:50648 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 04:18:31] Collection invoice1 already exists, returning existing collection.
[32mINFO[0m:     [21-09-2024 04:18:31] ::1:50670 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 04:40:50] ::1:51844 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 04:40:50] ::1:51844 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 04:40:50] Collection invoice1 already exists, returning existing collection.
[32mINFO[0m:     [21-09-2024 04:40:50] ::1:51845 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 04:41:04] ::1:51855 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 04:55:03] ::1:53930 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 04:55:03] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [21-09-2024 04:55:03] ::1:53930 - "POST /api/v1/collections/b7f1d4dd-1c7e-4dff-a40f-5a134e6d5354/add HTTP/1.1" 201
[32mINFO[0m:     [21-09-2024 05:14:10] ::1:55834 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 05:14:10] ::1:55834 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 05:14:10] Collection invoice1 already exists, returning existing collection.
[32mINFO[0m:     [21-09-2024 05:14:10] ::1:55835 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 05:14:24] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [21-09-2024 05:14:24] ::1:55853 - "POST /api/v1/collections/75070fdb-6914-4bc1-85a1-bc1858fe44e7/query HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 05:15:14] ::1:55903 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [21-09-2024 05:15:14] ::1:55903 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[36mDEBUG[0m:    [21-09-2024 05:15:14] Collection invoice2 already exists, returning existing collection.
[32mINFO[0m:     [21-09-2024 05:15:14] ::1:55904 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[33mWARNING[0m:  [21-09-2024 05:15:28] Number of requested results 5 is greater than number of elements in index 3, updating n_results = 3
[32mINFO[0m:     [21-09-2024 05:15:28] ::1:55915 - "POST /api/v1/collections/b7f1d4dd-1c7e-4dff-a40f-5a134e6d5354/query HTTP/1.1" 200
